Importing the right packages and dataset

In [1]:
import pandas as pd

tiktok_path = r"C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\tiktok\tiktok_phil_data.csv"
df_tiktok = pd.read_csv(tiktok_path)

df_tiktok.head()

,avatarThumbnail,cid,createTime,createTimeISO,detailedMentions/0/nickName,detailedMentions/0/profileUrl,detailedMentions/0/secUid,detailedMentions/0/userId,diggCount,input,likedByAuthor,mentions/0,pinnedByAuthor,repliesToId,replyCommentTotal,submittedVideoUrl,text,uid,uniqueId,videoWebUrl
0,https://p16-common-sign-sg.tiktokcdn-us.com/to...,7446935619391505160,1733874838,2024-12-10T23:53:58.000Z,NaN,NaN,NaN,NaN,17311,https://www.tiktok.com/@pontificalp/video/7446...,False,NaN,False,NaN,72,https://www.tiktok.com/@pontificalp/video/7446...,too much awareness can lead to depressed bro ngl,6963804721551328257,cryswanto,https://www.tiktok.com/@pontificalp/video/7446...
1,https://p16-common-sign-sg.tiktokcdn-us.com/to...,7447834298494796551,1734084061,2024-12-13T10:01:01.000Z,NaN,NaN,NaN,NaN,4322,https://www.tiktok.com/@pontificalp/video/7446...,False,NaN,False,NaN,11,https://www.tiktok.com/@pontificalp/video/7446...,We suffer more in our imagination than in reality,7408861602868790280,king.nothing83,https://www.tiktok.com/@pontificalp/video/7446...
2,https://p16-pu-sign-useast8.tiktokcdn-us.com/t...,7446900431962751787,1733866661,2024-12-10T21:37:41.000Z,NaN,NaN,NaN,NaN,2380,https://www.tiktok.com/@pontificalp/video/7446...,False,NaN,False,NaN,0,https://www.tiktok.com/@pontificalp/video/7446...,Ur changing my whole perspective on life,6794476210799625222,milthonrod24_life,https://www.tiktok.com/@pontificalp/video/7446...
3,https://p16-common-sign-useast2a.tiktokcdn-us....,7446836282825720608,1733851700,2024-12-10T17:28:20.000Z,NaN,NaN,NaN,NaN,489,https://www.tiktok.com/@pontificalp/video/7446...,False,NaN,False,NaN,1,https://www.tiktok.com/@pontificalp/video/7446...,Beautiful perspective,6894954217560916998,alex.prikna,https://www.tiktok.com/@pontificalp/video/7446...
4,https://p16-common-sign-va.tiktokcdn-us.com/to...,7447680767922586374,1734048328,2024-12-13T00:05:28.000Z,NaN,NaN,NaN,NaN,1587,https://www.tiktok.com/@pontificalp/video/7446...,False,NaN,False,NaN,6,https://www.tiktok.com/@pontificalp/video/7446...,I’m torn between wanting to know more and wish...,7426150478968882182,user9990860,https://www.tiktok.com/@pontificalp/video/7446...

Clean and Rename column titles

In [2]:
df_tiktok_cleaned = df_tiktok[[
    'uniqueId',
    'text',
    'diggCount',
    'createTimeISO',
    'videoWebUrl'
]].rename(columns={
    'uniqueId': 'username',
    'text': 'comment',
    'diggCount': 'like_count',
    'createTimeISO': 'time_posted',
    'videoWebUrl': 'comment_url'
})

df_tiktok_cleaned.head()

,username,comment,like_count,time_posted,comment_url
0,cryswanto,too much awareness can lead to depressed bro ngl,17311,2024-12-10T23:53:58.000Z,https://www.tiktok.com/@pontificalp/video/7446...
1,king.nothing83,We suffer more in our imagination than in reality,4322,2024-12-13T10:01:01.000Z,https://www.tiktok.com/@pontificalp/video/7446...
2,milthonrod24_life,Ur changing my whole perspective on life,2380,2024-12-10T21:37:41.000Z,https://www.tiktok.com/@pontificalp/video/7446...
3,alex.prikna,Beautiful perspective,489,2024-12-10T17:28:20.000Z,https://www.tiktok.com/@pontificalp/video/7446...
4,user9990860,I’m torn between wanting to know more and wish...,1587,2024-12-13T00:05:28.000Z,https://www.tiktok.com/@pontificalp/video/7446...

Clean the data types

Start with turning time_posted to datetime and like_count to interger

In [3]:
df_tiktok_cleaned['time_posted'] = pd.to_datetime(df_tiktok_cleaned['time_posted'])
df_tiktok_cleaned.dtypes

username                    object
comment                     object
like_count                   int64
time_posted    datetime64[ns, UTC]
comment_url                 object
dtype: object

Clean the comment text, first off by applying lowercasing

In [5]:
# Save a copy of the original comment
df_tiktok_cleaned['comment_original'] = df_tiktok_cleaned['comment']

# Convert comment text to lowercase
df_tiktok_cleaned['comment'] = df_tiktok_cleaned['comment'].str.lower()

df_tiktok_cleaned[['comment_original', 'comment']].head()

,comment_original,comment
0,too much awareness can lead to depressed bro ngl,too much awareness can lead to depressed bro ngl
1,We suffer more in our imagination than in reality,we suffer more in our imagination than in reality
2,Ur changing my whole perspective on life,ur changing my whole perspective on life
3,Beautiful perspective,beautiful perspective
4,I’m torn between wanting to know more and wish...,i’m torn between wanting to know more and wish...

cleaning for unnecessary emojis, urls or errors in the comment

In [7]:
import re

def clean_text_keep_emojis(text):
    # Remove URLs
    text = re.sub(r'http\S+|www.\S+', '', text)
    
    # Remove punctuation (except apostrophes)
    text = re.sub(r"[^\w\s'🧠💀😭😂🔥✨❤️😍🤔🤯😩😢😡😎🙏]", '', text)
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df_tiktok_cleaned['comment'] = df_tiktok_cleaned['comment'].apply(clean_text_keep_emojis)

df_tiktok_cleaned[['comment_original', 'comment']].head()

,comment_original,comment
0,too much awareness can lead to depressed bro ngl,too much awareness can lead to depressed bro ngl
1,We suffer more in our imagination than in reality,we suffer more in our imagination than in reality
2,Ur changing my whole perspective on life,ur changing my whole perspective on life
3,Beautiful perspective,beautiful perspective
4,I’m torn between wanting to know more and wish...,im torn between wanting to know more and wishi...

checking and handling missing variables

In [8]:
df_tiktok_cleaned.isnull().sum()

username            0
comment             0
like_count          0
time_posted         0
comment_url         0
comment_original    0
dtype: int64

checking and removing the duplicates

In [9]:
df_tiktok_cleaned.duplicated().sum()

np.int64(0)

In [10]:
df_tiktok_cleaned['comment'].duplicated().sum()

np.int64(240)

From the above we see that there are no dublicate rows, only repeated comments from different people who feel the same way about a topic which makes sense in pop culture.

So we'll, keep them for now but will add a column to flag them and use both columns when it's time to analyze later

In [11]:
df_tiktok_cleaned['is_duplicate_comment'] = df_tiktok_cleaned['comment'].duplicated()
df_tiktok_cleaned[['comment', 'is_duplicate_comment']].sample(5)

                                                comment  is_duplicate_comment
376   it's weird because you feel nothing but the no...                 False
771                             looooooool dreaminggggg                 False
1182  you cant know yourself or what this is about a...                 False
1457  all i want is a soft quiet lifea modest home a...                 False
89                                           true mannn                 False

Save the new cleaned tiktok file

In [12]:
df_tiktok_cleaned.to_csv("cleaned_tiktok_data.csv", index=False)